#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
  path: /logout

#redirect from the old site
contacts:
  path: /kontakty.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /contacts
    permanent: true

_razbrasyvateli-udobreniy:
  path: /razbrasyvateli-udobreniy.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/razbrasyvatel-udobreniy-mvu-1100
    permanent: true

_angary:
  path: /angary.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /angary
    permanent: true

_borona-pruzhinnaya:
  path: /borona-pruzhinnaya.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/borona-pruzhinnaya
    permanent: true

_opryskivatel-navesnoi-on-12:
  path: /opryskivatel-navesnoi-on-12.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/opryskivatel-navesnoi-on-12
    permanent: true

_podvoz-vody-zhku-kas:
  path: /podvoz-vody-zhku-kas.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /category/podvoz-vody-zhku-kas
    permanent: true

_pritsep-pozharnyi-ppv-2500:
  path: /pritsep-pozharnyi-ppv-2500.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/pritsep-pozharnyi-ppv-2500
    permanent: true

_selhoztehnika:
  path: /selhoztehnika.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /selhoztehnika/
    permanent: true

_kogda-i-kak-nastraivat-opryskivatel:
  path: /kogda-i-kak-nastraivat-opryskivatel.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/6
    permanent: true

_podkormka-ozimyh-azotnymi-udobreniyami:
  path: /podkormka-ozimyh-azotnymi-udobreniyami.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/26
    permanent: true

_sposoby-podkormki-ozimyh-kultur:
  path: /sposoby-podkormki-ozimyh-kultur.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/27
    permanent: true

_vybiraem-raspyliteli-dlya-opryskivatelya:
  path: /vybiraem-raspyliteli-dlya-opryskivatelya.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/8
    permanent: true

_rekomendatsii-po-vyboru-opryskivatelya:
  path: /rekomendatsii-po-vyboru-opryskivatelya.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/4
    permanent: true

_beskarkasnoe-arochnoe-stroitelstvo:
  path: /beskarkasnoe-arochnoe-stroitelstvo.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /angary/beskarkasnoe-arochnoe-stroitelstvo
    permanent: true

_stroitelstvo-zernohranilishh:
  path: /stroitelstvo-zernohranilishh.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /angary/stroitelstvo-zernohranilishh-i-ovoshehranilishh
    permanent: true

_voprosy-po-stroitelstvu-angarov-selhoztehnike:
  path: /voprosy-po-stroitelstvu-angarov-selhoztehnike.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /
    permanent: true

_borona-rotatsionnaya65:
  path: /borona-rotatsionnaya65.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/borona-rotatsionnaya-tip3
    permanent: true

_osobennosti-maloobemnogo-opriskivaniya:
  path: /osobennosti-maloobemnogo-opriskivaniya.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/54
    permanent: true

_zapasnyye-chasti:
  path: /zapasnyye-chasti.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /spare-parts
    permanent: true

_proizvodstvo-opryskivateley:
  path: /proizvodstvo-opryskivateley.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/16
    permanent: true

_karkasnye-i-beskarkasnye-angary:
  path: /karkasnye-i-beskarkasnye-angary.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /angary/karkasnye-i-beskarkasnye-angary
    permanent: true

_podvoz-vody:
  path: /podvoz-vody.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/podvoz-vody
    permanent: true

_davlenie-i-ravnomernost-raspileniya-part2:
  path: /davlenie-i-ravnomernost-raspileniya-part2.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/45
    permanent: true

_o-razmere-kapel-part2:
  path: /o-razmere-kapel-part2.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/46
    permanent: true

_obrabotka-metalla:
  path: /obrabotka-metalla.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /services
    permanent: true

_osobennosti-rashoda-rabochei-zhidkosti-part2:
  path: /osobennosti-rashoda-rabochei-zhidkosti-part2.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/53
    permanent: true

_chem-grozit-nesobludenie-skorostnogo-regima-part2:
  path: /chem-grozit-nesobludenie-skorostnogo-regima-part2.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/42
    permanent: true

_politika-konfidencialnosti:
  path: /politika-konfidencialnosti.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /politika-konfidencialnosti
    permanent: true

_vneshnie-factori-part2:
  path: /vneshnie-factori-part2.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/39
    permanent: true

_agronomu-na-zametku:
  path: /agronomu-na-zametku.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /agronomu-na-zametku
    permanent: true

_okzh:
  path: /okzh.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/okzh
    permanent: true

_sistema-parallelnogo-vozhdeniya-agronavigator:
  path: /sistema-parallelnogo-vozhdeniya-agronavigator.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/sistema-parallelnogo-vozhdeniya-agronavigator
    permanent: true

_grabli-voroshilki-senovoroshilka:
  path: /grabli-voroshilki-senovoroshilka.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/grabli-voroshilki-senovoroshilka
    permanent: true

_opryskivatel-ventilyatornyi-sadovyi:
  path: /opryskivatel-ventilyatornyi-sadovyi.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/opryskivatel-ventilyatornyi-sadovyi-600
    permanent: true

_otechestvennye-i-zarubezhnye-opryskivateli:
  path: /otechestvennye-i-zarubezhnye-opryskivateli.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/20
    permanent: true

_agregat-kombinirovannyi-diskovyi:
  path: /agregat-kombinirovannyi-diskovyi.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/agregat-kombinirovannyi-diskovyi
    permanent: true

_mashiny-dlya-vneseniya-udobreniy:
  path: /mashiny-dlya-vneseniya-udobreniy.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/mashiny-dlya-vneseniya-udobreniy
    permanent: true

_samohodnyi-razbrasyvatel-udobreniy:
  path: /samohodnyi-razbrasyvatel-udobreniy.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/samohodnyi-razbrasyvatel-udobreniy
    permanent: true

_leasing:
  path: /leasing.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /leasing
    permanent: true

_o-kompanii-agro-teh:
  path: /o-kompanii-agro-teh.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /about
    permanent: true

_opryskivatel-pritsepnoi-op-28:
  path: /opryskivatel-pritsepnoi-op-28.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/opryskivatel-pritsepnoi-op-28
    permanent: true

_smesi-v-bake-opryskivatelya:
  path: /smesi-v-bake-opryskivatelya.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/11
    permanent: true

_opryskivatel-pritsepnoi-ventilyatornyi-opv-2000:
  path: /opryskivatel-pritsepnoi-ventilyatornyi-opv-2000.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/opryskivatel-pritsepnoi-ventilyatornyi-opv-2000
    permanent: true

_osobennosti-protsessa-opryskivaniya:
  path: /osobennosti-protsessa-opryskivaniya.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /articles/12
    permanent: true

_opryskivatel-gerbitsidnyi:
  path: /opryskivatel-gerbitsidnyi.php
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /tech/opryskivatel-gerbitsidnyi
    permanent: true
